services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379