name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    GO_VERSION: 1.22.x

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [01-todo-list]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION}}

      - name: Change directory
        run: cd ${{ matrix.project }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
