name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    GO_VERSION: 1.22.x

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [01-todo-list, 02-backend-api, 03-web-scraper]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ matrix.project }}/go.mod
          cache-dependency-path: ${{ matrix.project }}/go.sum

      - name: Build
        working-directory: ${{ matrix.project }}
        run: go build -v ./...

      - name: Test
        working-directory: ${{ matrix.project }}
        run: go test -v ./...
